# Specify version format
version: "3.1.0-{build}"

os: Visual Studio 2015

# specify custom environment variables
environment:
  VISP_SOURCE_DIR: C:\projects\visp\visp
  VISP_BUILD_DIR: C:\projects\visp\build

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  # All external dependencies are installed in C:\projects\3rdparty
  - mkdir C:\projects\3rdparty
  - cd C:\projects\3rdparty

# clone directory
clone_folder: %VISP_SOURCE_DIR%

build_script:
  - md %VISP_BUILD_DIR%
  - cd %VISP_BUILD_DIR%
  - cmake -G "Visual Studio 14 2015 Win64" %VISP_SOURCE_DIR%
  - cmake --build . --config Release --target visp_modules
#  - ctest


