# Specify version format
version: "{build}"

os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  # All external dependencies are installed in C:\projects\deps
  - mkdir C:\projects\deps
  - cd C:\projects\deps

# clone directory
clone_folder: C:\projects\visp


build_script:
  - md C:\projects\visp\build
  - cd C:\projects\visp\build
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build ..\visp --config Release —-target visp_modules
#  - ctest


