# Specify version format
version: "3.1.0-{build}"

os: Visual Studio 2015

# to add several platforms to build matrix
platform:
- x64

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  # All external dependencies are installed in C:\projects\deps
  - mkdir C:\projects\deps
  - cd C:\projects\deps

  # visp-images
  - git clone https://github.com/lagadic/ViSP-images C:\projects\deps\visp-images
  - set VISP_INPUT_IMAGE_PATH=C:\projects\deps\visp-images

  # opencv
  - cmd: ECHO "INSTALL OPENCV:"
  - cmd: choco install OpenCV

# visp clone directory
clone_folder: C:\projects\visp\visp

before_build:
  - cmd: SET ARCH=x64
  # setup visp
  - cmd: SET VISP_DLL_DIR=C:\projects\visp\build\install\%ARCH%\vc14\bin
  - cmd: SET PATH=%VISP_DLL_DIR%;%PATH%
  
  # setup opencv
#  - cmd: IF EXIST C:\OpenCV* CD C:\OpenCV*
#  - cmd: SET OPENCV_ROOT_PATH=%CD%\opencv
#  - cmd: SET OPENCV_DIR=%OPENCV_ROOT_PATH%\build
#  - cmd: SET OPENCV_DLL_DIR=%OPENCV_ROOT_PATH%\build\%ARCH%\vc14\bin
#  - cmd: SET PATH=%OPENCV_DLL_DIR%;%PATH%
#  - cmd: ECHO %OPENCV_DLL_DIR%
#  - dir %OPENCV_DLL_DIR%

build_script:
  - dir C:\projects\deps
  - dir C:\tools
  - dir C:\tools\opencv\build\install\%ARCH%\vc14\bin
  - echo %VISP_INPUT_IMAGE_PATH%
  - dir %VISP_INPUT_IMAGE_PATH%
  - md C:\projects\visp\build
  - cd C:\projects\visp\build
  - cmake -G "Visual Studio 14 2015 Win64" ..\visp -DBUILD_EXAMPLES=OFF -DBUILD_TUTORIALS=OFF -DBUILD_DEMOS=OFF
#  - cmake --build . --config Release --target visp_modules
  - cmake --build . --config Release --target install
  - ctest
  - dir C:\projects\visp\build\install\%ARCH%\vc14\bin
  - C:\projects\visp\build\modules\core\Release\testReadImage


